# Generated by Django 4.2.4 on 2023-08-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Block_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=200)),
                ('Floor', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='Block_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.block_location'),
        ),
    ]
